secrets:
  - name: datadog-api-key

services:
  - type: web
    name: to-do app
    env: node
    branch: main
    buildCommand: cd server && npm ci
    startCommand: cd server && node index.js
    runtime: node_20
envVars:
  - key: DD_API_KEY
    fromSecret: datadog-api-key
  - key: DD_SITE
    value: ap2.datadoghq.com
  - key: DD_AGENTLESS
    value: "true"
  - key: DD_SERVICE
    value: to-do app
  - key: DD_ENV
    value: production
  - key: DD_VERSION
    value: "1.0.0"
  - key: DD_TRACE_ENABLED
    value: "true"
  - key: DD_TRACE_DEBUG
    value: "true"
  - key: NODE_VERSION
    value: "20"
    