services:
  - type: web
    name: todo-backend
    env: node
    branch: main
    buildCommand: cd server && npm ci
    startCommand: cd server && npm start
    runtime: node_20
    envVars:
      - key: NEW_RELIC_LICENSE_KEY
        fromSecret: newrelic-license-key
