services:
  - type: web
    name: todo-backend
    env: docker
    branch: main
    dockerfilePath: server/Dockerfile
    envVars:
      - key: NEW_RELIC_LICENSE_KEY
        fromSecret: newrelic-license-key
