secrets:
  - name: newrelic-license-key

services:
  - type: web
    name: todo-backend
    env: node
    branch: main
    buildCommand: cd server && npm ci
    startCommand: cd server && npm start
    runtime: node_20
    envVars:
      - key: NEW_RELIC_LICENSE_KEY
        fromSecret: newrelic-license-key
      - key: NEW_RELIC_APP_NAME
        value: To-Do App
      - key: NEW_RELIC_LOG
        value: stdout
      - key: NEW_RELIC_LOG_LEVEL
        value: info
      - key: NODE_VERSION
        value: "20"
