secrets:
  - name: datadog-api-key

services:
  - type: web
    name: to-do app
    env: node
    branch: main
    buildCommand: cd server && npm ci
    startCommand: cd server && node index.js
    healthCheckPath: "/health"
    runtime: node_20
envVars:
  - key: DD_API_KEY
    fromSecret: 7ced6304e53cb93d211411a9ab30f07c
  - key: DD_SITE
    value: ap2.datadoghq.com
  - key: DD_TRACE_AGENT_URL
    value: https://trace.agent.ap2.datadoghq.com/api/v0.2/traces
  - key: DD_SERVICE
    value: to-do app
  - key: DD_ENV
    value: production
  - key: DD_VERSION
    value: "1.0.0"
  - key: DD_TRACE_ENABLED
    value: "true"
  - key: DD_TRACE_DEBUG
    value: "true"
  - key: NODE_VERSION
    value: "20"
    